openapi: 3.0.0
info:
  description: API tracker productos
  version: 1.0.0
  title: Api productos AXPO
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
paths:
  /product:
    post:
      summary: tracker de productos
      responses:
        '200':
          description: producto creado con exito
        '400':
          description: 'invalid input, object invalid'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Product'

    get:
      summary: search products
      operationId: searchProducts
      description: |
        By passing in the appropriate options, you can search for
        available products in the system
      parameters:
        - in: query
          name: product_code
          description: pass an optional search string for looking up inventory
          required: false
          schema:
            type: string

        - in: query
          name: startdate
          description: search by startdate
          schema:
            type: string
            format: date

        - in: query
          name: enddate
          description: search by end date
          schema:
            type: string
            format: date

      responses:
        '200':
          description: search results matching criteria
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
        '400':
          description: bad input parameters

components:
  schemas:
    Product:
      type: object
      required:
        - productCode
        - productVersion
        - type
        - status
        - CLIs
        - calendars
        - currency
        - units
        - splitType
        - descriptionBillFix
        - descriptionBillFree
        - navConcept
      properties:
        productCode:
          type: string
          title: ProductCode
          example: BloqueFirme261120191130320001
        productVersion:
          type: string
          title: productVersion
          description: productVersion
        status:
          type: string
          title: ''
          description: 'Posibles valores Draft, Active, Old, Cancelled'
          enum:
            - Draft
            - Active
            - Old
            - Cancelled
        previousStatus:
          type: string
          title: previousStatus
          description: previousStatus
        type:
          type: string
          title: type
          description: type
        subtype:
          type: string
          title: subtype
          description: subtype
        descriptionBillFix:
          type: string
          title: descriptionBillFix
          description: descriptionBillFix
        descriptionBillFree:
          type: string
          title: descriptionBillFree
          description: descriptionBillFree
        navConcept:
          type: string
          title: navConcept
          description: navConcept
        billSection:
          type: string
          title: billSection
          description: billSection
        startDate:
          type: string
          format: date
        updateStartDateWithCLI:
          type: boolean
          title: ''
          description: ''
          default: false
        endDate:
          type: string
          format: date
        updateEndDateWithCLI:
          type: boolean
          title: ''
          description: ''
          default: false
        lastSettlementDate:
          type: string
          format: date
        meta:
          $ref: '#/components/schemas/meta'
        calendars:
          $ref: '#/components/schemas/calendar'
        currency:
          type: string
          title: ''
          description: 'Posibles valores EUR, USD, GBP'
          enum:
            - EUR
            - USD
            - GBP
        units:
          type: string
          title: ''
          description: 'Posibles valores MWh, kWh, MMBTU, Gj'
          enum:
            - MWh
            - kWh
            - MMBTU
            - Gj
        lambda:
          type: string
          title: ''
          description: ''
        dependencies:
          type: array
          items:
            $ref: '#/components/schemas/dependencies'
        offsets:
          type: array
          items:
            $ref: '#/components/schemas/offsets'
        splitType:
          type: string
          title: ''
          description: 'Posibles valores FixPercentage,Forecast,BestConsumption,MoleculeService'
          enum:
            - FixPercentage
            - Forecast
            - BestConsumption
            - MoleculeService
        CLIs:
          type: array
          items:
            $ref: '#/components/schemas/cli'
        prices:
          $ref: '#/components/schemas/price'
        quantities:
          type: array
          title: ''
          description: 'Para Bloque Firme, Cobertura y Tolerancia solo tiene un elemento, para Servicio de Molecula puede tener entre 0 y el total de thresholds'
          items:
            $ref: '#/components/schemas/quantity'
        thresholds:
          type: array
          title: ''
          description: 'Bandas del Servicio de Molecula, margenes de error de la Bonificacion por nominacion. Para limite de Tolerancia solo admite un elemento'
          items:
            $ref: '#/components/schemas/threshold'
        moleculeTaxes:
          type: array
          items:
            $ref: '#/components/schemas/moleculeTax'
          title: ''
          description: Para Bloque Firme y Servicio de Molecula
        fees:
          $ref: '#/components/schemas/fee'

        digitalPayment:
          $ref: '#/components/schemas/digitalPayment'

        fixPrices:
          type: array
          title: ''
          description: ''
          items:
            $ref: '#/components/schemas/range'
        TPA:
          $ref: '#/components/schemas/TPA'

    meta:
      type: object
      title: ''
      description: Se crearan un numero de metas entre 2 y 10
      properties:
        meta01:
          type: string
          title: ''
          description: ''
        meta02:
          type: string
          title: ''
          description: ''
    calendar:
      type: object
      title: ''
      description: ''
      properties:
        calendarWhenDays:
          type: string
          title: ''
          description: ''
        calendarLiqPeriod:
          type: string
          title: ''
          description: ''
        calendarCalcSubPeriod:
          type: string
          title: ''
          description: ''
        invoiceCalendar:
          $ref: '#/components/schemas/invoiceCalendar'
    invoiceCalendar:
      type: object
      title: ''
      description: ''
      properties:
        calendarInvDays:
          type: array
          title: ''
          description: ''
          items:
            type: string
            format: date
        dynamicInvCalendar:
          type: string
          title: ''
          description: ''
        invoiceCalendarLiqOffset:
          $ref: '#/components/schemas/invoiceCalendarLiqOffset'
    invoiceCalendarLiqOffset:
      type: object
      title: ''
      description: ''
      properties:
        source:
          type: string
          title: ''
          description: ''
        operation:
          type: string
          title: ''
          description: ''
        numDay:
          type: number
          title: ''
          description: ''
    dependencies:
      type: object
      title: ''
      properties:
        dependencyType:
          type: string
          title: ''
          description: 'Posibles valores Product, Settlement Line'
          enum:
            - Product
            - Settlement Line
        product:
          type: string
          title: ''
        dependentAttribute:
          type: string
          title: ''
          enum:
            - Quantity
            - PeriodProductAmountGrandTotal
        dependencyCalc:
          type: string
          title: ''
          enum:
            - Sum
            - Sub
            - Mult
            - Div
    offsets:
      type: object
      title: ''
      description: ''
      properties:
        from:
          type: string
          format: date
        to:
          type: string
          format: date
        offset:
          type: number
    price:
      type: object
      title: ''
      properties:
        priceType:
          type: string
          title: ''
          enum:
            - precio1
            - precio2
            - General
            - Electrico
            - Termico
            - SuperReducidoIndustrial
            - ReducidoIndustrial
        formula:
          type: string
          title: ''
        margin:
          type: number
          title: ''
    cli:
      type: object
      title: ''
      description: ''
      properties:
        identifier:
          type: string
          title: ''
          description: ''
        percentages:
          type: array
          title: ''
          description: ''
          items:
            $ref: '#/components/schemas/range'
    range:
      type: object
      title: ''
      properties:
        from:
          type: string
          format: date
        to:
          type: string
          format: date
        value:
          type: number
    quantity:
      type: object
      title: ''
      description: ''
      properties:
        from:
          type: string
          format: date
        to:
          type: string
          format: date
        quantity:
          type: number
        type:
          type: string
          title: ''
          description: 'Cobertura y Tolerancia. Posibles valores Abs, %'
          enum:
            - Abs
            - '%'
        reference:
          type: string
          title: ''
          description: 'Cobertura y Tolerancia//Posibles valores Forecast,BestConsumption. Si Type=Abs , Abs.'
          enum:
            - Abs
            - Forecast
            - BestConsumption
    threshold:
      type: object
      title: ''
      description: ''
      properties:
        from:
          type: string
          format: date
        to:
          type: string
          format: date
        limitTo:
          type: number
        type:
          type: string
          title: ''
          description: 'Posibles valores Abs, %. Para Bonificacion por nominacion solo %.'
          enum:
            - Abs
            - '%'
        formula:
          type: string
          title: ''
        margin:
          type: number
    fee:
      type: object
      title: ''
      description: ''
      properties:
        prorrate:
          type: string
        prices:
          type: array
          items:
            $ref: '#/components/schemas/range'
    moleculeTax:
      type: object
      properties:
        moleculeTaxConcept:
          type: string
          title: ''
          description: ''
        moleculeTaxValue:
          type: string
          title: ''
          description: ''
    TPA:
      type: object
      title: ''
      description: 'ATR Distribucion, ATR Upstream'
      properties:
        passthrough:
          type: boolean
          title: ''
          description: ''
          default: false
        concepts:
          type: array
          items:
            $ref: '#/components/schemas/concept'
    concept:
      type: object
      title: ''
      properties:
        id:
          type: string
          title: ''
          description: ''
        subtype:
          type: string
          title: ''
          description: ''
        qds:
          type: array
          items:
            $ref: '#/components/schemas/qd'
        qdCalctype:
          type: string
          title: ''
          description: ''
        qdM-1:
          type: number
          title: ''
          description: ''
        qdM-2:
          type: number
          title: ''
          description: ''
        tollPresureGroup:
          type: number
          title: ''
          description: ''
          enum:
            - 1
            - 2
            - 3
        tollConsumptionStep:
          type: number
          title: ''
          description: ''
          enum:
            - 0
            - 1
            - 2
            - 3
            - 4
            - 5
            - 6
        vtPrice:
          $ref: '#/components/schemas/price'

        ftPrice:
          $ref: '#/components/schemas/price'

        transportFixTermPrice:

          $ref: '#/components/schemas/range'

        regasFixTermPrice:

          $ref: '#/components/schemas/range'

        type:
          type: string
          enum:
            - MeterRent
            - Other
            - TFTV
        amounts:
          type: array
          items:
            $ref: '#/components/schemas/amount'
        codConceptoB70in:
          type: array
          items:
            type: number
        codConceptoB70out:
          type: array
          items:
            type: number
    digitalPayment:
      type: object
      title: ''
      description: Cobertura
      properties:
        prorrate:
          type: string
          title: ''
          description: ''
        formula:
          type: string
          title: ''
          description: ''
        margin:
          type: number
          title: ''
          description: ''
    qd:
      type: object
      title: ''
      description: ''
      properties:
        from:
          type: string
          format: date
        to:
          type: string
          format: date
        qd:
          type: number
    amount:
      type: object
      title: ''
      description: ''
      properties:
        from:
          type: string
          format: date
        to:
          type: string
          format: date
        amount:
          type: number
